### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by carlossoy** [kamilion/customizer#181]
Hello, thank you very much for sharing your knowledge, this program I like very much pear in the last version I have been impossible to install it.
I'm sending this fault message to the terminal.

[sudo] password for carlos: 
* Read Configuration file: /etc/customizer.conf
Traceback (most recent call last):
  File "/usr/sbin/customizer-gui", line 29, in <module>
    import lib.config as config
  File "/usr/share/customizer/lib/config.py", line 45, in <module>
    KERNEL = '{}'.format(conf.get('saved', 'KERNEL', fallback='default'))
TypeError: get() got an unexpected keyword argument 'fallback'

carlos@mate:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Greetings and thank you !!

**Comment by kamilion** [comment]
#171 was fixed on June 13th in commit https://github.com/kamilion/customizer/commit/180c533dfd9eaa332ac4d1bad4c4fd3075027b0c

How was the package built?

**Comment by carlossoy** [comment]
I used the installation method posted on the blog. I have installed the Mate version of Ubuntu but it has always worked for me for the previous versions

**Comment by dlarue** [comment]
I'm running/building/installing from git source on Lubuntu 17.04.3 kernel version 4.10

**Comment by kamilion** [comment]
Sorry, you're going to have to link to whatever blog post you were following or check out the comments on  #171 to get modern build instructions.

`make PYTHON=python3 PYQT=5 deb`
or
`make PYTHON=python3 PYQT=5; sudo make install`
should do it.
