### ISSUE TITLE
Got an error when run

### ISSUE THREAD

**Issue by Allen-B1** [kamilion/customizer#186]
I got this:
```
* Configuration file does not exist: /etc/customizer.conf
* Read Configuration file: /etc/customizer.conf
Traceback (most recent call last):
  File "/usr/sbin/customizer-gui", line 29, in <module>
    import lib.config as config
  File "/usr/share/customizer/lib/config.py", line 46, in <module>
    PURGE_KERNEL = '{}'.format(conf.get('saved', 'PURGE_KERNEL'))
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 700, in _interpolate_some
    p = rest.find("%")
AttributeError: 'bool' object has no attribute 'find'
```

**Comment by kamilion** [comment]
#171 was fixed on June 13th in commit 180c533

Pull from master or devel, then
`make PYTHON=python3 PYQT=5 deb`
or
`make PYTHON=python3 PYQT=5; sudo make install`
should build everything.

**Comment by Allen-B1** [comment]
I was trying to install the Debian packages. Are those available?

**Comment by kamilion** [comment]
`make PYTHON=python3 PYQT=5 deb` will build a debian package from the source tree.
The deb is installable with dpkg -i.

I don't know how @clearkimura was generating 'official' packages before I took over the repository; and packaging isn't my strong point. Sorry.

**Comment by Allen-B1** [comment]
Oh

**Comment by Allen-B1** [comment]
Thanks!
